/**
 * Comprehensive Car Database
 * Extracted for readability and maintainability.
 */

const CAR_DATABASE = {
    "Acura": [
        "ILX",
        "Integra",
        "MDX",
        "NSX",
        "RDX",
        "RLX",
        "TLX",
        "TSX",
        "ZDX"
    ],
    "Alfa Romeo": [
        "4C",
        "8C Competizione",
        "Giulia",
        "Giulietta",
        "Stelvio",
        "Tonale",
        "Mito"
    ],
    "Aston Martin": [
        "DB11",
        "DBS",
        "DBX",
        "Vantage",
        "Rapide",
        "Vanquish",
        "Valkyrie"
    ],
    "Audi": [
        "A1",
        "A3",
        "A4",
        "A4 Allroad",
        "A5",
        "A6",
        "A6 Allroad",
        "A7",
        "A8",
        "Q2",
        "Q3",
        "Q4 e-tron",
        "Q5",
        "Q7",
        "Q8",
        "Q8 e-tron",
        "R8",
        "TT",
        "e-tron GT",
        "S1",
        "S3",
        "S4",
        "S5",
        "S6",
        "S7",
        "S8",
        "SQ2",
        "SQ5",
        "SQ7",
        "SQ8",
        "RS3",
        "RS4",
        "RS5",
        "RS6",
        "RS7",
        "RS Q3",
        "RS Q8",
        "TT RS"
    ],
    "Bentley": [
        "Bentayga",
        "Continental GT",
        "Flying Spur",
        "Mulsanne"
    ],
    "BMW": [
        "1 Series",
        "2 Series",
        "3 Series",
        "4 Series",
        "5 Series",
        "6 Series",
        "7 Series",
        "8 Series",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "XM",
        "Z4",
        "i3",
        "i4",
        "i5",
        "i7",
        "iX",
        "iX1",
        "iX3",
        "M2",
        "M3",
        "M4",
        "M5",
        "M8",
        "X3 M",
        "X4 M",
        "X5 M",
        "X6 M"
    ],
    "Bugatti": [
        "Chiron",
        "Veyron",
        "Divo",
        "Bolide"
    ],
    "Buick": [
        "Enclave",
        "Encore",
        "Envision",
        "Regal"
    ],
    "Cadillac": [
        "CT4",
        "CT5",
        "CT6",
        "Escalade",
        "Lyriq",
        "XT4",
        "XT5",
        "XT6"
    ],
    "Chevrolet": [
        "Blazer",
        "Camaro",
        "Colorado",
        "Corvette",
        "Cruze",
        "Equinox",
        "Malibu",
        "Silverado 1500",
        "Silverado 2500",
        "Spark",
        "Suburban",
        "Tahoe",
        "Trailblazer",
        "Traverse",
        "Volt",
        "Bolt EV"
    ],
    "Chrysler": [
        "300",
        "Pacifica",
        "Voyager"
    ],
    "Citro\u00ebn": [
        "C3",
        "C4",
        "C5 Aircross",
        "Berlingo",
        "C3 Aircross",
        "SpaceTourer"
    ],
    "Dacia": [
        "Duster",
        "Logan",
        "Sandero",
        "Spring",
        "Jogger"
    ],
    "Dodge": [
        "Challenger",
        "Charger",
        "Durango",
        "Hornet",
        "Journey"
    ],
    "Ferrari": [
        "296 GTB",
        "488 GTB",
        "812 Superfast",
        "F8 Tributo",
        "Portofino",
        "Roma",
        "SF90 Stradale",
        "Purosangue"
    ],
    "Fiat": [
        "500",
        "500L",
        "500X",
        "Panda",
        "Tipo",
        "Ducato"
    ],
    "Ford": [
        "Bronco",
        "Bronco Sport",
        "Edge",
        "Escape",
        "Expedition",
        "Explorer",
        "F-150",
        "F-250",
        "F-350",
        "Fiesta",
        "Focus",
        "Mustang",
        "Mustang Mach-E",
        "Puma",
        "Ranger",
        "Transit"
    ],
    "Genesis": [
        "G70",
        "G80",
        "G90",
        "GV60",
        "GV70",
        "GV80"
    ],
    "GMC": [
        "Acadia",
        "Canyon",
        "Hummer EV",
        "Sierra 1500",
        "Terrain",
        "Yukon"
    ],
    "Honda": [
        "Accord",
        "Civic",
        "CR-V",
        "Fit",
        "HR-V",
        "Insight",
        "Odyssey",
        "Passport",
        "Pilot",
        "Ridgeline",
        "Jazz"
    ],
    "Hyundai": [
        "Accent",
        "Elantra",
        "Ioniq 5",
        "Ioniq 6",
        "Kona",
        "Palisade",
        "Santa Cruz",
        "Santa Fe",
        "Sonata",
        "Tucson",
        "Venue",
        "i10",
        "i20",
        "i30"
    ],
    "Infiniti": [
        "Q50",
        "Q60",
        "QX50",
        "QX55",
        "QX60",
        "QX80"
    ],
    "Jaguar": [
        "E-PACE",
        "F-PACE",
        "F-TYPE",
        "I-PACE",
        "XE",
        "XF",
        "XJ"
    ],
    "Jeep": [
        "Cherokee",
        "Compass",
        "Gladiator",
        "Grand Cherokee",
        "Renegade",
        "Wrangler",
        "Wagoneer"
    ],
    "Kia": [
        "Carnival",
        "Ceed",
        "EV6",
        "EV9",
        "Forte",
        "K5",
        "Niro",
        "Picanto",
        "Rio",
        "Seltos",
        "Sorento",
        "Soul",
        "Sportage",
        "Stinger",
        "Telluride"
    ],
    "Lamborghini": [
        "Aventador",
        "Huracan",
        "Urus",
        "Revuelto"
    ],
    "Land Rover": [
        "Defender",
        "Discovery",
        "Discovery Sport",
        "Range Rover",
        "Range Rover Evoque",
        "Range Rover Sport",
        "Range Rover Velar"
    ],
    "Lexus": [
        "ES",
        "GS",
        "GX",
        "IS",
        "LC",
        "LS",
        "LX",
        "NX",
        "RC",
        "RX",
        "RZ",
        "UX"
    ],
    "Lincoln": [
        "Aviator",
        "Corsair",
        "Nautilus",
        "Navigator"
    ],
    "Lotus": [
        "Emira",
        "Evija",
        "Eletre"
    ],
    "Maserati": [
        "Ghibli",
        "Grecale",
        "Levante",
        "MC20",
        "Quattroporte"
    ],
    "Mazda": [
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-50",
        "CX-60",
        "CX-7",
        "CX-9",
        "CX-90",
        "Mazda2",
        "Mazda3",
        "Mazda6",
        "MX-5 Miata"
    ],
    "McLaren": [
        "570S",
        "600LT",
        "720S",
        "765LT",
        "Artura",
        "GT",
        "P1"
    ],
    "Mercedes-Benz": [
        "A-Class",
        "B-Class",
        "C-Class",
        "CLA",
        "CLE",
        "CLS",
        "E-Class",
        "EQA",
        "EQB",
        "EQC",
        "EQE",
        "EQS",
        "G-Class",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "GLS",
        "S-Class",
        "SL",
        "V-Class",
        "AMG A 35",
        "AMG A 45",
        "AMG C 43",
        "AMG C 63",
        "AMG E 53",
        "AMG E 63",
        "AMG G 63",
        "AMG GT",
        "AMG SL 63"
    ],
    "MINI": [
        "Clubman",
        "Convertible",
        "Countryman",
        "Hardtop 2 Door",
        "Hardtop 4 Door",
        "Paceman"
    ],
    "Mitsubishi": [
        "Eclipse Cross",
        "Lancer",
        "Mirage",
        "Outlander",
        "Outlander Sport",
        "Pajero"
    ],
    "Nissan": [
        "Altima",
        "Ariya",
        "Armada",
        "Frontier",
        "GT-R",
        "Juke",
        "Kicks",
        "Leaf",
        "Maxima",
        "Murano",
        "Navara",
        "Pathfinder",
        "Patrol",
        "Qashqai",
        "Rogue",
        "Sentra",
        "Titan",
        "Versa",
        "Z"
    ],
    "Opel": [
        "Astra",
        "Corsa",
        "Crossland",
        "Grandland",
        "Insignia",
        "Mokka"
    ],
    "Peugeot": [
        "2008",
        "208",
        "3008",
        "308",
        "408",
        "5008",
        "508"
    ],
    "Porsche": [
        "718 Boxster",
        "718 Cayman",
        "911",
        "Cayenne",
        "Macan",
        "Panamera",
        "Taycan"
    ],
    "Ram": [
        "1500",
        "2500",
        "3500",
        "ProMaster"
    ],
    "Renault": [
        "Arkana",
        "Captur",
        "Clio",
        "Kadjar",
        "Kangoo",
        "Koleos",
        "Megane",
        "Zoe"
    ],
    "Rolls-Royce": [
        "Cullinan",
        "Dawn",
        "Ghost",
        "Phantom",
        "Wraith"
    ],
    "Skoda": [
        "Enyaq",
        "Fabia",
        "Kamiq",
        "Karoq",
        "Kodiaq",
        "Octavia",
        "Scala",
        "Superb"
    ],
    "Subaru": [
        "Ascent",
        "BRZ",
        "Crosstrek",
        "Forester",
        "Impreza",
        "Legacy",
        "Outback",
        "Solterra",
        "WRX"
    ],
    "Suzuki": [
        "Ignis",
        "Jimny",
        "Swift",
        "SX4 S-Cross",
        "Vitara"
    ],
    "Tesla": [
        "Model 3",
        "Model S",
        "Model X",
        "Model Y",
        "Cybertruck",
        "Roadster"
    ],
    "Toyota": [
        "4Runner",
        "Avalon",
        "Aygo",
        "bZ4X",
        "Camry",
        "C-HR",
        "Corolla",
        "Corolla Cross",
        "Crown",
        "GR86",
        "Highlander",
        "Hilux",
        "Land Cruiser",
        "Mirai",
        "Prius",
        "RAV4",
        "Sequoia",
        "Sienna",
        "Supra",
        "Tacoma",
        "Tundra",
        "Venza",
        "Yaris"
    ],
    "Volkswagen": [
        "Arteon",
        "Atlas",
        "Caddy",
        "Crafter",
        "Golf",
        "ID.3",
        "ID.4",
        "ID.5",
        "ID.Buzz",
        "Jetta",
        "Passat",
        "Polo",
        "Taos",
        "Tiguan",
        "Touareg",
        "Transporter"
    ],
    "Volvo": [
        "C40 Recharge",
        "EX30",
        "EX90",
        "S60",
        "S90",
        "V60",
        "V90",
        "XC40",
        "XC60",
        "XC90"
    ],
    "ZAZ": [
        "Lanos",
        "Sens",
        "Vida",
        "Forza"
    ]
};
